### ISSUE TITLE
Animal station output bug

### ISSUE THREAD

**Issue by zymex22** [nullre/Project-RimFactory-Revived#42]
For some reason Aniaml Station (sherer, milker, generic) when harvesting it drop where it get harvested and not using output cell?

Thingclass
ProjectRimFactory.AnimalStation.Building_Shearer
ProjectRimFactory.AnimalStation.Building_Milker
ProjectRimFactory.AnimalStation.Building_GenericBodyResourceGatherer

i dont know if it worked earlier, just got some reports on it this week.

**Comment by nullre** [comment]
it seems that output cell is not used from the earlier.

https://github.com/nullre/Project-RimFactory-Revived/commit/b431115176857275b6c80aaf45d88bf09dd9ac88#diff-f2868cc43a00882f47b988527547de66

With this commit, ProjectRimFactory.Common.CompOutputAdjustable has been added.
The output cell can be selected, but the selected output cell is not used.
Therefore, it occurs after 23-4-20 of this commit.

fixed in fix_#42 branch.

**Comment by zymex22** [comment]
this works can PR and close
